# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jubesio.github.io
email: jubesio@viamyeye.co.uk
description: jubesio.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jubesio.github.io/" # the base hostname & protocol for your site
twitter_username: ijubeso
github_username:  jubesio

# Build settings
markdown: kramdown
